name: Tatiana Catalioto
markdown: redcarpet
baseurl: ""
exclude: [
  .git,
  .gitignore,
  Thumbs.db,
  CNAME,
  scss,
  .sass-cache,
  package.json,
  Gruntfile.js,
  node_modules,
  readme.md
]

excerpt_separator: <!--more-->