name: Tatiana Catalioto
markdown: redcarpet
baseurl: ""
exclude: [
  .git,
  .gitignore,
  Thumbs.db,
  CNAME,
  scss,
  .sass-cache,
  package.json,
  gruntfile.js,
  node_modules,
  readme.md
]

prose:
  rooturl: '_posts'
  siteurl: 'http://malavita.github.io/'
  relativeLinks: 'http://malavita.github.io/links.jsonp'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add Categories"
          placeholder: "Add Categories"
          alterable: true
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "image"
        field:
          element: "text"
          label: "Add Image to Post"
          placeholder: "Image path (relative to /images/)"
          alterable: true
      - name: "excerpt_separator"
        field:
          element: "hidden"
          value: "<!--more-->"
