name: Tatiana Catalioto
markdown: redcarpet
baseurl: ""
exclude: [
  .git,
  .gitignore,
  Thumbs.db,
  CNAME,
  scripts,
  postcss,
  .sass-cache,
  package.json,
  bower.json,
  gruntfile.js,
  node_modules,
  readme.md
]

excerpt_separator: <!--more-->
